sonar.organization=pharmadash-org
sonar.projectKey=pharmadash-org_pharmadash-frontend
sonar.projectName=PharmaDash Frontend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,src/environments/**,src/main.ts

sonar.typescript.lcov.reportPaths=coverage/pharmadash/lcov.info
sonar.javascript.lcov.reportPaths=coverage/pharmadash/lcov.info
